# Generated by Django 5.2 on 2025-05-08 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_owner'),
        ('users', '0003_profile_location_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='reviews',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('owner', 'project')},
        ),
    ]
